spring:
  jpa:
    show-sql: true

  config:
    additional-location: file:/home/${user}/.credentials/my-cloud-dev/

logging:
  level:
    org.springframework.jdbc.core: DEBUG

auth:
  clean-timer:
    schedule: "0 */5 * * * *"

canary:
  timer:
    web: "-"

docker:
  timer:
    dockerhub: "-"

email:
  sender: "test@awae.ch"