spring:
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG

db.cloud:
  url: jdbc:postgresql://localhost:21004/postgres
  username: postgres
  password: postgres

canary:
  timer:
    web: "-"

docker:
  timer:
    dockerhub: "-"

email:
  sender: "test@awae.ch"
  timer:
    send: "-"

mailjet:
  api-key-public: dummy
  api-key-secret: dummy

features:
  default-state: true